version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        depends_on:
            - app
        ports:
            - 8080:8080
        volumes:
            - ../src:/src:cached
            - ./nginx/default.conf:/etc/nginx/default.conf:cached
            - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:cached
    app:
        build:
            context: ./phpv7.4.3
        image: phpv743
        container_name: phpv743
        volumes:
            - ../src:/src:cached
            - ./phpv7.4.3/php.ini:/usr/local/etc/php/php.ini:cached
