version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: speed_test01_nginx
        depends_on:
            - php
        ports:
            - 80:80
        volumes:
            - ../../src:/src:cached
            - ../../src/logs/nginx_error.log:/var/log/nginx/error.log:cached
            - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:cached

    php:
        build:
            context: ./php
        volumes:
            - ../../src:/src:cached
            - ./php/php.ini:/usr/local/etc/php/php.ini
